#!/bin/sh /etc/rc.common

START=20

start() {
        companion=`find /sys/devices -type f -name companion | head -n 1`
        if [ -f $companion ] ; then
                echo "Setting 3G modem to full speed mode..."
                echo 2 > $companion
        fi
        insmod GobiSerial
        insmod GobiNet
#	ifconfig usb0 up
#        man3g start-session --auto-connect
#	sleep 5
#	3g_connmgr &
}

stop() {
#	killall 3g_connmgr
#        man3g stop-session
#        ifconfig usb0 down
        rmmod GobiNet
        rmmod GobiSerial
}
