#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

USE_PROCD=1
PROG=/usr/sbin/telnetd

has_root_pwd() {
        local pwd=$([ -f "$1" ] && cat "$1")
              pwd="${pwd#*root:}"
              pwd="${pwd%%:*}"

        test -n "${pwd#[\!x]}"
}

get_root_home() {
        local homedir=$([ -f "$1" ] && cat "$1")
        homedir="${homedir#*:*:0:0:*:}"

        echo "${homedir%%:*}"
}

start_service() {
        procd_open_instance
        procd_set_param command "$PROG" -F
        procd_close_instance
}
