#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ipsec_pre[-1]
	set ucitrack.ipsec_pre="ipsec_pre"
	uci set ucitrack.@ipsec_pre[-1].init=ipsec_pre
	uci set ucitrack.@ipsec_pre[-1].exec='/etc/init.d/ipsec_pre restart'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
