#!/bin/bash

# If a git push fails with an odd error 22, http error 404 or whatever, use this:
# git config http.postBuffer 524288000

OPUNTIA_CFG="config-opuntia-4.7"
if [ ! -f .config ] ; then
	cp -f $OPUNTIA_CFG .config
elif [ -f .config ] && ! diff .config $OPUNTIA_CFG > /dev/null ; then
	echo "Configuration change detected!"
	echo "Backing up your previous configuration to .config.old..."
	sleep 3
	mv -f .config .config.old
	cp -f $OPUNTIA_CFG .config
fi

# Update feeds if Luci is not present
if [ ! -f feeds/luci.index ] ; then
	./scripts/feeds update -a
	# Feeds script runs defconfig so we need to re-copy .config again.
	cp -f $OPUNTIA_CFG .config
	./scripts/feeds install -a
	make oldconfig
fi

# OpenWRT sucks for building in parallel!
# The toolchain must be single-thread built
make tools/install
if [ "$?" != "0" ] ; then
	echo "Failed to build tools! Trying again..."
	sleep 5
	make tools/install
	if [ "$?" != "0" ] ; then
		echo "Failed to build tools!"
		exit 5
	fi
fi

# The rest can *mostly* be built in parallel
let retries=5

while [ $((retries)) -gt 0 ] ; do
	make -j $((`cat /proc/cpuinfo | grep bogomips | wc -l` * 2))
	if [ "$?" != "0" ] ; then
		exit 0
	fi
	echo "Failed to build! Probably just a transient error, trying again ($retries left)"
	let retries=retries-1
done
