#!/bin/sh
#
# Copyright (C) 2013 ImageStream Internet Solutions, Inc.
#

# Set up MultiWAN for failover to WWAN cellular with WAN as the primary default.

uci batch <<EOF
delete multiwan.@mwanfw[]
delete multiwan.@mwanfw[]
delete multiwan.@mwanfw[]
delete multiwan.@mwanfw[]
delete multiwan.wan2
delete multiwan.wan
set multiwan.config=multiwan
set multiwan.config.enabled=1
set multiwan.config.default_route=wan
set multiwan.wan=interface
set multiwan.wan.weight=disable
set multiwan.wan.health_interval=10
set multiwan.wan.timeout=3
set multiwan.wan.health_fail_retries=3
set multiwan.wan.health_recovery_retries=3
set multiwan.wan.dns=auto
set multiwan.wan.icmp_hosts=arp_gateway
set multiwan.wan.failover_to=wwan
set multiwan.wan.restart_ipsec_on_fail=1
set multiwan.wan.restart_ipsec_on_recovery=1
set multiwan.wwan=interface
set multiwan.wwan.weight=disable
set multiwan.wwan.health_interval=10
set multiwan.wwan.timeout=3
set multiwan.wwan.health_fail_retries=3
set multiwan.wwan.health_recovery_retries=3
set multiwan.wwan.dns=auto
set multiwan.wwan.icmp_hosts=arp_gateway
set multiwan.wwan.failover_to=wan
EOF

uci commit multiwan

exit 0
