#!/bin/bash

check_clients() {
        status=/tmp/client-status.$1
        hostapd_cli -i $1 status > $status
        eval $(cat $status | grep num_sta)

        let clients=0
        for i in "${num_sta[@]}"; do
                let clients=clients+i
        done
        rm $status
        if [ $clients -eq 0 ]; then
                if [ $can_reset -eq 1 ] ; then
                        #reset
                        logger "WiFi-Watchdog-$2: No clients connected, resetting..."
                        kill $(cat /var/run/wifi-$2.pid)
                        let can_reset=0
                fi
        else
                let can_reset=1
        fi
}

let can_reset=0
while sleep 600; do
	:;
# This is a bad idea for busy APs providing public wifi as procd will mark
# the hostapd process as crash looping
# I think the problem may be solved now with a missed IRQ patch 
#	check_clients $1 $2
done
