#!/bin/sh /etc/rc.common
#
#

START=15

start() {
	rm -rf /var/licenses
	mkdir /var/licenses

	if [ -d /etc/licenses ] ; then
        	cd /etc/licenses
        	for file in *; do
                	echo "Extracting license file $file..."
                	/usr/bin/gpg --batch --no-tty --quiet --homedir /lib/security/el_security \
                        	--output /var/licenses/$file \
                        	--decrypt /etc/licenses/$file
        	done
        	cd
	fi
}
