#!/bin/sh /etc/rc.common
#
#

START=40

start() {
	# Password protect the api
	grep -qe '^/api/:' /etc/httpd.conf
	if [ "$?" != "0" ] ; then
		echo '/api/:admin:$p$root' >> /etc/httpd.conf
	fi

	uci set uhttpd.main.index_page='index.html index.php'
	uci set uhttpd.main.interpreter=.php=/usr/bin/php-cgi
	uci set uhttpd.main.config=/etc/httpd.conf

	uci commit uhttpd

	# Restart if running
	pidof uhttpd > /dev/null && /etc/init.d/uhttpd restart
}

stop() {
	# Remove the php interpreter
	uci set uhttpd.main.index_page='index.html'
	uci delete uhttpd.main.interpreter
	uci delete uhttpd.main.config

	uci commit uhttpd

	# Restart if running
	pidof uhttpd > /dev/null && /etc/init.d/uhttpd restart
}
