#!/bin/sh
#
# Copyright (C) 2013 ImageStream Internet Solutions, Inc.
#

uci batch <<EOF
add firewall rule
set firewall.@rule[-1]="rule"
set firewall.@rule[-1].target="ACCEPT"
set firewall.@rule[-1].src="wan"
set firewall.@rule[-1].proto="tcp"
set firewall.@rule[-1].dest_port="23"
set firewall.@rule[-1].name="Allow-Telnet"
EOF

uci commit firewall

exit 0
