#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ipsec_pre[-1]
	add ucitrack ipsec_pre
	set ucitrack.@ipsec_pre[-1].init=ipsec_pre
	set ucitrack.@ipsec_pre[-1].exec='/etc/init.d/ipsec_pre restart'
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
# Why is this needed? It should enable by default!
/etc/init.d/ipsec enable
/etc/init.d/ipsec start
exit 0
