#!/bin/sh
#
# Copyright (C) 2013 ImageStream Internet Solutions, Inc.
#

# Add a wwan cellular interface

#uci batch <<EOF
#set network.wwan=interface
#set network.wwan.proto=qmi
#set network.wwan.ifname=usb0
#set network.wwan.provider=att_broadband
#set network.wwan.service=auto
#set network.wwan.apn=broadband
#set network.wwan.force_link=1
#set network.wwan.auto=0
#add_list firewall.@zone[1].network=wwan
#EOF
#
#uci commit network
#uci commit firewall

exit 0

