#!/bin/sh /etc/rc.common
#
#
# ImageStream Cloud Bootstrap for WiFi APs

START=99
STOP=99

start() {
        (
#		/etc/init.d/rssileds stop
                /usr/lib/bootstrap/bootstrap.php
#		sleep 30
#		/etc/init.d/rssileds start
        ) 2>&1 | logger &
}
