#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=90

. /usr/share/libubox/jshn.sh

function process_imagestream() {
	# If an SSID is set then bail
	uci -q get wireless.@wifi-iface[0].ssid > /dev/null && return 1

	is_dev="mmcblk0"
	grep $is_dev /proc/partitions > /dev/null 2>&1 || return 1
	json_load "$(dd if=/dev/mmcblk0 bs=1k count=4 skip=$(($(awk '$4 == "mmcblk0" { print $3}' < /proc/partitions) - 4)) | dd bs=1 skip=256 2>/dev/null)"
	json_get_vars radio0_ssid radio0_key radio0_mode radio0_wds
	[ -z $radio0_ssid ] && return 1
	[ -z $radio0_key ] && return 1
	[ -z $radio0_mode ] && return 1
	[ -z $radio0_wds ] && return 1
	logger "Adding default SSID"
	uci set wireless.default_radio0=wifi-iface
	uci set wireless.default_radio0.network="lan"
	uci set wireless.default_radio0.device="radio0"
	uci set wireless.default_radio0.mode="$radio0_mode"
	uci set wireless.default_radio0.encryption="psk2"
	uci set wireless.default_radio0.ssid="$radio0_ssid"
	uci set wireless.default_radio0.key="$radio0_key"
	uci set wireless.default_radio0.wds="$radio0_wds"
	uci commit wireless

	# Also set the hostname
	HN=$(uci get system.@system[0].hostname)
	if [ "$HN" == "Opuntia" ] ; then
		RN=$(echo $radio0_ssid | cut -d '_' -f 2)
		logger "Setting default hostname"
		uci set system.@system[0].hostname="${radio0_mode}-$RN"
		uci commit system
	fi

	# Also set the default fallback ip if sta mode 
	if [ "$radio0_mode" == "sta" ] ; then
		FB=$(uci get network.lan.fb_ipaddr)
		if [ "$FB" == "10.10.199.1" ] ; then
			logger "Changing default fallback ip"
			uci set network.lan.fb_ipaddr="10.10.199.2"
			uci commit network
		fi
	fi

	reload_config
	return 0
}

boot() {
        case $(board_name) in
	raspberrypi,4-compute-module)
		process_imagestream || return 0
	;;
        esac
}
