#!/usr/bin/lua

mfile = "/tmp/sysinfo/model"
echo = 1
model = {}
gpio = {}
gpio2 = {}

pin = nil
pin2 = nil

model[1] = "703n"
gpio[1] = 8
model[2] = "3020"
gpio[2] = 8
model[3] = "11u"
gpio[3] = 8
model[4] = "3040"
gpio[4] = 18
model[5] = "3220"
gpio[5] = 6
model[6] = "3420"
gpio[6] = 6
model[7] = "wdr3500"
gpio[7] = 12
model[8] = "wdr3600"
gpio[8] = 12
model[9] = "wdr4300"
gpio[9] = 21
gpio2[9] = 22
model[10] = "wdr4310"
gpio[10] = 21
gpio2[10] = 22
model[11] = "842"
gpio[11] = 6

numodel = 11

local file = io.open(mfile, "r")
if file == nil then
	return
end

line = file:read("*line")
file:close()
line = line:lower()

for i=1,numodel do
	start, ends = line:find(model[i])
	if start ~= nil then
		if model[i] == "3420" then
			start, ends = line:find("v1")
			if start ~= nil then
				pin = gpio[i]
				pin2 = nil
			else
				pin = 4
				pin2 = nil
			end
		else
			pin = gpio[i]
			pin2 = gpio2[i]
		end
		if model[i] == "3220" then
			start, ends = line:find("v1")
			if start ~= nil then
				pin = gpio[i]
				pin2 = nil
			else
				pin = 8
				pin2 = nil
			end
		else
			pin = gpio[i]
			pin2 = gpio2[i]
		end

		break
	end
end

if pin ~= nil then
	local tfile = io.open("/tmp/gpiopin", "w")
	if pin2 ~= nil then
		tfile:write("GPIOPIN=\"", pin, "\"")
		tfile:write("GPIOPIN2=\"", pin2, "\"")
	else
		tfile:write("GPIOPIN=\"", pin, "\"")
	end
	tfile:close()
end
