#!/bin/sh

local PINGTIME=$(uci get cbi_file.Network.pingtime)
if [ -z $PINGTIME ]; then
	PINGTIME=2
fi

echo "*/$PINGTIME * * * * /etc/root" > /etc/crontabs/root
echo "*/1 * * * * /etc/wrtbwmon setup br-lan" >> /etc/crontabs/root
echo "*/5 * * * * /etc/wrtbwmon update /tmp/usage.db peak" >> /etc/crontabs/root

local BACK=$(uci get monitor.bandwidth.backup)
if [ $BACK -ne 0 ]; then
	echo "1 */"$BACK" * * * /etc/wrtbwmon backup /tmp/usage.db /etc/config/usage.db" >> /etc/crontabs/root
fi

local RESET=$(uci get monitor.bandwidth.mon_reset)
if [ $RESET = "month" ]; then
	DAY=$(uci get monitor.bandwidth.day_mon)
	HOUR=$(uci get monitor.bandwidth.hour)
	echo "5 $HOUR $DAY * * /etc/wrtbwmon reset /tmp/usage.db /etc/config/usage.db" >> /etc/crontabs/root
fi

if [ $RESET = "week" ]; then
	DAY=$(uci get monitor.bandwidth.day_wk)
	HOUR=$(uci get monitor.bandwidth.hour)
	echo "5 $HOUR * * $DAY /etc/wrtbwmon reset /tmp/usage.db /etc/config/usage.db" >> /etc/crontabs/root
fi

if [ $RESET = "day" ]; then
	HOUR=$(uci get monitor.bandwidth.hour)
	echo "5 $HOUR * * * /etc/wrtbwmon reset /tmp/usage.db /etc/config/usage.db" >> /etc/crontabs/root
fi

if [ $RESET = "hour" ]; then
	echo "5 * * * * /etc/wrtbwmon reset /tmp/usage.db /etc/config/usage.db" >> /etc/crontabs/root
fi

/etc/init.d/cron restart