#!/bin/sh

save_var() {
	rm -f /etc/variable.file
	KEEPALIVE=0
	echo 'NETCREATE="'"$NETCREATE"'"' >> /etc/variable.file
	echo 'NETSIERRA="'"$NETSIERRA"'"' >> /etc/variable.file
	echo 'SIERRACTIVE="'"$SIERRACTIVE"'"' >> /etc/variable.file
	echo 'QMIWWAN="'"$QMIWWAN"'"' >> /etc/variable.file
	echo 'KEEPALIVE="'"$KEEPALIVE"'"' >> /etc/variable.file
	echo 'RBDELAY="'"$RBDELAY"'"' >> /etc/variable.file
}

power_toggle() {
	if [ -f "/tmp/gpiopin" ]; then
		source /tmp/gpiopin
		if [ -z $GPIOPIN2 ]; then
			echo 0 > /sys/class/gpio/gpio$GPIOPIN/value
			sleep 2
			echo 1 > /sys/class/gpio/gpio$GPIOPIN/value
		else
			echo 0 > /sys/class/gpio/gpio$GPIOPIN/value
			echo 0 > /sys/class/gpio/gpio$GPIOPIN2/value
			sleep 2
			echo 1 > /sys/class/gpio/gpio$GPIOPIN/value
			echo 1 > /sys/class/gpio/gpio$GPIOPIN2/value
		fi
	else
		if [ $1 = "wan" ]; then
			ifup wan
		fi
	fi
}

[ -f "/etc/variable.file" ] || return
source /etc/variable.file

log() {
	logger -t "Connection Keep Alive : " "$@"
}

local ALIVE=$(uci get cbi_file.Network.alive)

if [ -z $ALIVE ]; then
	return
fi
if [ $ALIVE = 0 ]; then
	return
fi
if [ -z $KEEPALIVE ]; then
	return
fi
if [ $KEEPALIVE = 0 ]; then
	return
fi

local PINGWAIT=$(uci get cbi_file.Network.pingwait)
local PINGNUM=$(uci get cbi_file.Network.pingnum)
local PINGSERV1=$(uci get cbi_file.Network.pingserv1)
local PINGSERV2=$(uci get cbi_file.Network.pingserv2)

if ! ping -q -c $PINGNUM -W $PINGWAIT $PINGSERV1 > /dev/null; then
	if [ x"$PINGSERV2" != x ]; then
		if ping -q -c $PINGNUM -W $PINGWAIT $PINGSERV2 > /dev/null; then
			log "Connection is Alive"
			return
		fi
	fi
	if [ $ALIVE = 4 ]; then
		log "Connection is Down. Doing a modem power toggle (if supported) or a WAN restart"
		save_var
		pkill getsig
		uci set cbi_file.Version.getsig="0"
		uci commit cbi_file
        	power_toggle wan
	fi
	if [ $ALIVE = 3 ]; then
		log "Connection is Down. Doing a WAN restart"
		save_var
		pkill getsig
		uci set cbi_file.Version.getsig="0"
		uci commit cbi_file
        	ifup wan
	fi
	if [ $ALIVE = 2 ]; then 
		save_var
		/etc/wrtbwmon backup /tmp/usage.db /etc/config/usage.db
		power_toggle
        	reboot -f
	else
		log "Connection is Down" 
	fi
else
	log "Connection is Alive"  
fi
