#!/bin/sh

rm -f /tmp/qmistate.wwan1
echo 'NETCREATE="'"0"'"' > /etc/variable.file
echo 'NETSIERRA="'"0"'"' >> /etc/variable.file
echo 'SIERRACTIVE="'"0"'"' >> /etc/variable.file
echo 'QMIWWAN="'"0"'"' >> /etc/variable.file
echo 'KEEPALIVE="'"0"'"' >> /etc/variable.file
echo 'RBDELAY="'"1"'"' >> /etc/variable.file

uci delete cbi_file.Version
uci set cbi_file.Version=version
uci set cbi_file.Version.ver="{CODENAME}"

source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION="$(uci get cbi_file.Version.ver)"
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'"$DISTRIB_REVISION"'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release

local AUTH=$(uci get cbi_file.Network.auth)
if [ -z $AUTH ]; then
	uci set cbi_file.Network.auth="0"
fi
local ALIVE=$(uci get cbi_file.Network.alive)
if [ -z $ALIVE ]; then
	uci set cbi_file.Network.alive="0"
fi

local PTIME=$(uci get cbi_file.Network.pingtime)
if [ -z $PTIME ]; then
	uci set cbi_file.Network.pingtime="2"
	uci set cbi_file.Network.pingwait="10"
	uci set cbi_file.Network.pingnum="1"
	uci set cbi_file.Network.pingserv1="8.8.8.8"
fi

local DELAY=$(uci get cbi_file.Network.delay)
if [ -z $DELAY ]; then
	uci set cbi_file.Network.delay="60"
fi

echo 'TOGGLE="'"0"'"' > /tmp/toggle.file
uci set cbi_file.Version.log="0"
uci set cbi_file.Version.getsig="0"

uci commit cbi_file

[ -f "/etc/config/usage.db" ] && cp /etc/config/usage.db /tmp/usage.db

/etc/gpiomodel
/etc/monitor

uci set system.@system[-1].hostname="ROOter"
uci set system.@system[-1].cronloglevel="9"

local BTN=$(uci get system.@button[-1].button)
if [ -z $BTN ]; then
	uci add system button
	uci set system.@button[-1].button=reset
	uci set system.@button[-1].action=released
	uci set system.@button[-1].handler="/etc/btnaction reset_short"
	uci set system.@button[-1].min=5
	uci set system.@button[-1].max=15

	uci add system button
	uci set system.@button[-1].button=reset
	uci set system.@button[-1].action=released
	uci set system.@button[-1].handler="/etc/btnaction reset_long"
	uci set system.@button[-1].min=17
	uci set system.@button[-1].max=60

	uci add system button
	uci set system.@button[-1].button=wps
	uci set system.@button[-1].action=released
	uci set system.@button[-1].handler="/etc/btnaction qss_short"
	uci set system.@button[-1].min=0
	uci set system.@button[-1].max=3

	uci add system button
	uci set system.@button[-1].button=wps
	uci set system.@button[-1].action=released
	uci set system.@button[-1].handler="/etc/btnaction qss_long"
	uci set system.@button[-1].min=5
	uci set system.@button[-1].max=10
fi

uci commit system

echo "-" > /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "No Modem Present" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo " " >> /tmp/status.file
echo " " >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file

echo "0" > /tmp/bootend.file


