#!/bin/sh

log() {
	logger -t "Sigstop " "$@"
}

DEVICE=$1

if [ -f "/tmp/cmd.at" ]; then
	read line < /tmp/cmd.at
	export ATCMD="$line"
	OX=$(gcom -d $DEVICE -s /etc/run-at.gcom 2>/dev/null)
	echo "$OX" > /tmp/result.at

	rm -f /tmp/cmd.at
fi

if [ -f "/tmp/modecmd.at" ]; then
	read line < /tmp/modecmd.at
	export ATCMD="$line"
	OX=$(gcom -d $DEVICE -s /etc/run-at.gcom 2>/dev/null)
	rm -f /tmp/modecmd.at
	uci set cbi_file.Version.cmode="1"
	uci commit cbi_file
fi

if [ -f "/tmp/bandcmd.at" ]; then
	read line < /tmp/bandcmd.at
	export ATCMD="$line"
	OX=$(gcom -d $DEVICE -s /etc/run-at.gcom 2>/dev/null)
	rm -f /tmp/bandcmd.at
fi

if [ -f "/tmp/smssend.at" ]; then
	read line < /tmp/smssend.at
	export ATCMD="$line"
	OX=$(gcom -d $DEVICE -s /etc/sendsms-at.gcom 2>/dev/null)
	rm -f /tmp/smssend.at
fi

local SMS=$(uci get cbi_file.Version.sms)
if [ $SMS = 1 ]; then
	export ATCMD="AT+CPMS=\"SM\""
	SX=$(gcom -d $DEVICE -s /etc/run-at.gcom 2>/dev/null)
	export USED=$(echo "$SX" | awk -F[,\ ] '/^\+CPMS:/ {print $2}')
	MAXED=$(echo "$SX" | awk -F[,\ ] '/^\+CPMS:/ {print $3}')
	local NUMB=$(uci get cbi_file.Version.smsmsg)
	if [ $USED != $NUMB ]; then
		FX=$SX
		log "Reread SMS Messages as number has changed"
		uci set cbi_file.Version.smsmsg=$USED

		INDEX=0
		CNTR=0
		while [ $CNTR -lt $USED ]; do
			export SLOT="$INDEX"
			OZ=$(gcom -v -d $DEVICE -s /etc/readsms-at.gcom 2>/dev/null)
			FX=$FX$OZ
			if [ "x$OZ" != "x" ]; then
				CNTR=`expr $CNTR + 1`
			fi
			INDEX=`expr $INDEX + 1`
		done
		echo "$FX" > /tmp/smsresult.at

		uci set cbi_file.Version.smsread="0"
		uci commit cbi_file
	fi
fi

exit 0