#!/bin/sh
#
# Copyright (C) 2013-2014 ImageStream Internet Solutions, Inc.
#

# Password protect the api
echo '/api/:admin:$p$root' >> /etc/httpd.conf

uci batch <<EOF
set uhttpd.main.index_page='index.html index.php'
set uhttpd.main.interpreter=.php=/usr/bin/php-cgi
set uhttpd.main.config=/etc/httpd.conf
EOF

uci commit uhttpd

exit 0

