#!/bin/sh
#
# Copyright (C) 2013 ImageStream Internet Solutions, Inc.
#

#uci batch <<EOF
#add dhcp dhcp
#set dhcp.@dhcp[-1]='dhcp'
#set dhcp.@dhcp[-1].start=100
#set dhcp.@dhcp[-1].leasetime=12h
#set dhcp.@dhcp[-1].limit=150
#set dhcp.@dhcp[-1].interface='Clients'
#EOF
#
#uci commit dhcp

# If lan ignore is not set we set it. Generally you shouldn't run DHCP server on a single
# ethernet interface AP.
uci get dhcp.lan.ignore > /dev/null 2>&1 || {
	uci set dhcp.lan.ignore='1'
	uci commit dhcp
}

exit 0


