#!/bin/sh
#
# Copyright (C) 2013 ImageStream Internet Solutions, Inc.
#

#uci batch <<EOF
#set network.lan.proto='static'
#set network.lan.ipaddr=10.10.199.1
#set network.lan.netmask=255.255.255.0
#EOF
#
#uci commit network

exit 0

